/*
** EPITECH PROJECT, 2020
** cpp_rush2_2019
** File description:
** TODO: add description
*/
#ifndef CPP_RUSH2_2019_PAPAXMASCONVEYORBELT_HPP
#define CPP_RUSH2_2019_PAPAXMASCONVEYORBELT_HPP

#endif //CPP_RUSH2_2019_PAPAXMASCONVEYORBELT_HPP
