/*
** EPITECH PROJECT, 2020
** strace
** File description:
** syscalls
*/

#include "ftrace.h"

const syscalls_t syscalls[] = {
    {0, "read", {INT, STRING, ULONG, NO_ARG, NO_ARG, NO_ARG}},
    {1, "write", {INT, STRING, ULONG, NO_ARG, NO_ARG, NO_ARG}},
    {2, "open", {STRING, INT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {3, "close", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {4, "stat", {STRING, STRUCT_STAT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {5, "fstat", {INT, STRUCT_STAT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {6, "lstat", {STRING, STRUCT_STAT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {7, "poll", {STRUCT_POLL_FD, UINT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {8, "lseek", {INT, ULONG, INT, NO_ARG, NO_ARG, NO_ARG}},
    {9, "mmap", {PTR, ULONG, INT, INT, INT, ULONG}},
    {10, "mprotect", {PTR, ULONG, INT, NO_ARG, NO_ARG, NO_ARG}},
    {11, "munmap", {PTR, ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {12, "brk", {ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {13, "rt_sigaction",
        {INT, STRUCT_SIGACTION, STRUCT_SIGACTION, NO_ARG, NO_ARG, NO_ARG}},
    {14, "rt_sigprocmask",
        {INT, STRUCT_SIGSET, STRUCT_SIGSET, ULONG, NO_ARG, NO_ARG}},
    {15, "rt_sigreturn", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {16, "ioctl", {INT, ULONG, INT, NO_ARG, NO_ARG, NO_ARG}},
    {17, "pread64", {INT, STRING, ULONG, ULONG, NO_ARG, NO_ARG}},
    {18, "pwrite64", {INT, STRING, ULONG, ULONG, NO_ARG, NO_ARG}},
    {19, "readv", {INT, STRUCT_IOVEC, INT, NO_ARG, NO_ARG, NO_ARG}},
    {20, "writev", {INT, STRUCT_IOVEC, INT, NO_ARG, NO_ARG, NO_ARG}},
    {21, "access", {STRING, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {22, "pipe", {PTR, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {23, "select", {INT, FDSET, FDSET, FDSET, STRUCT_TIMEVAL, NO_ARG}},
    {24, "sched_yield", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {25, "mremap", {PTR, ULONG, ULONG, INT, PTR, NO_ARG}},
    {26, "msync", {PTR, ULONG, INT, NO_ARG, NO_ARG, NO_ARG}},
    {27, "mincore", {PTR, ULONG, STRING, NO_ARG, NO_ARG, NO_ARG}},
    {28, "madvise", {PTR, ULONG, INT, NO_ARG, NO_ARG, NO_ARG}},
    {29, "shmget", {INT, ULONG, INT, NO_ARG, NO_ARG, NO_ARG}},
    {30, "shmat", {INT, STRING, INT, NO_ARG, NO_ARG, NO_ARG}},
    {31, "shmctl", {INT, INT, STRUCT_SHMID_DS, NO_ARG, NO_ARG, NO_ARG}},
    {32, "dup", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {33, "dup2", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {34, "pause", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {35, "nanosleep",
        {STRUCT_TIMESPEC, STRUCT_TIMESPEC, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {36, "getitimer", {INT, STRUCT_ITIMERVAL, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {37, "alarm", {UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {38, "setitimer",
        {INT, STRUCT_ITIMERVAL, STRUCT_ITIMERVAL, NO_ARG, NO_ARG, NO_ARG}},
    {39, "getpid", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {40, "sendfile", {INT, INT, PTR, ULONG, NO_ARG, NO_ARG}},
    {41, "socket", {INT, INT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {42, "connect", {INT, STRUCT_SOCKADDR, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {43, "accept", {INT, STRUCT_SOCKADDR, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {44, "sendto", {INT, PTR, ULONG, INT, STRUCT_SOCKADDR, UINT}},
    {45, "recvfrom", {INT, PTR, ULONG, INT, STRUCT_SOCKADDR, UINT}},
    {46, "sendmsg", {INT, STRUCT_MSGHDR, INT, NO_ARG, NO_ARG, NO_ARG}},
    {47, "recvmsg", {INT, STRUCT_MSGHDR, INT, NO_ARG, NO_ARG, NO_ARG}},
    {48, "shutdown", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {49, "bind", {INT, STRUCT_SOKADDR, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {50, "listen", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {51, "getsockname", {INT, STRUCT_SOCKADDR, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {52, "getpeername", {INT, STRUCT_SOCKADDR, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {53, "socketpair", {INT, INT, INT, PTR, NO_ARG, NO_ARG}},
    {54, "setsockopt", {INT, INT, INT, STRING, UINT, NO_ARG}},
    {55, "getsockopt", {INT, INT, INT, STRING, UINT, NO_ARG}},
    {56, "clone", {PTR, PTR, INT, PTR, PTR, PTR}},
    {57, "fork", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {58, "vfork", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {59, "execve", {STRING, STRING, STRING, NO_ARG, NO_ARG, NO_ARG}},
    {60, "exit", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {61, "wait4", {INT, PTR, INT, STRUCT_RUSAGE, NO_ARG, NO_ARG}},
    {62, "kill", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {63, "uname", {STRUCT_OLD_UTSNAME, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {64, "semget", {INT, INT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {65, "semop", {INT, STRUCT_SEMBUF, ULONG, NO_ARG, NO_ARG, NO_ARG}},
    {66, "semctl", {INT, INT, INT, INT, NO_ARG, NO_ARG}},
    {67, "shmdt", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {68, "msgget", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {69, "msgsnd", {INT, STRUCT_MSGBUF, ULONG, INT, NO_ARG, NO_ARG}},
    {70, "msgrcv", {INT, STRUCT_MSGBUF, ULONG, LONG, INT, NO_ARG}},
    {71, "msgctl", {INT, INT, STRUCT_MSQID_DS, NO_ARG, NO_ARG, NO_ARG}},
    {72, "fcntl", {INT, INT, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {73, "flock", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {74, "fsync", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {75, "fdatasync", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {76, "truncate", {STRING, ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {77, "ftruncate", {INT, ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {78, "getdents", {UINT, STRUCT_LINUX_DIRENT, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {79, "getcwd", {STRING, ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {80, "chdir", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {81, "fchdir", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {82, "rename", {STRING, STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {83, "mkdir", {STRING, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {84, "rmdir", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {85, "creat", {STRING, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {86, "link", {STRING, STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {87, "unlink", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {88, "symlink", {STRING, STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {89, "readlink", {STRING, STRING, ULONG, NO_ARG, NO_ARG, NO_ARG}},
    {90, "chmod", {STRING, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {91, "fchmod", {INT, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {92, "chown", {STRING, UINT, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {93, "fchown", {INT, UINT, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {94, "lchown", {STRING, UINT, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {95, "umask", {UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {96, "gettimeofday",
        {STRUCT_TIMEVAL, STRUCT_TIMEZONE, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {97, "getrlimit", {INT, STRUCT_RLIMIT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {98, "getrusage", {INT, STRUCT_RUSAGE, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {99, "sysinfo", {STRUCT_SYSINFO, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {100, "times", {STRUCT_TMS, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {101, "ptrace", {INT, INT, PTR, PTR, NO_ARG, NO_ARG}},
    {102, "getuid", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {103, "syslog", {INT, STRING, INT, NO_ARG, NO_ARG, NO_ARG}},
    {104, "getgid", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {105, "setuid", {UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {106, "setgid", {UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {107, "geteuid", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {108, "getegid", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {109, "setpgid", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {110, "getppid", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {111, "getpgrp", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {112, "setsid", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {113, "setreuid", {UINT, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {114, "setregid", {UINT, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {115, "getgroups", {INT, PTR, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {116, "setgroups", {INT, PTR, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {117, "setresuid", {UINT, UINT, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {118, "getresuid", {PTR, PTR, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {119, "setresgid", {UINT, UINT, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {120, "getresgid", {PTR, PTR, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {121, "getpgid", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {122, "setfsuid", {UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {123, "setfsgid", {UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {124, "getsid",
        {UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {125, "capget",
        {CAP_USER_HEAD, CAP_USER_DATA, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {126, "capset",
        {CAP_USER_HEAD, CAP_USER_DATA, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {127, "rt_sigpending",
        {STRUCT_SIGSET, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {128, "rt_sigtimedwait",
        {STRUCT_SIGSET,
            STRUCT_SIGINFO, STRUCT_TIMESPEC, NO_ARG, NO_ARG, NO_ARG}},
    {129, "rt_sigqueueinfo",
        {INT, INT, STRUCT_SIGINFO, NO_ARG, NO_ARG, NO_ARG}},
    {130, "rt_sigsuspend",
        {STRUCT_SIGSET, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {131, "sigaltstack",
        {STRUCT_STACK, STRUCT_STACK, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {132, "utime", {STRING, STRUCT_UTIMBUF, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {133, "mknod", {STRING, UINT, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {134, "uselib", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {135, "personality", {ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {136, "ustat", {ULONG, STRUCT_USTAT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {137, "statfs", {STRING, STRUCT_STATFS, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {138, "fstatfs", {INT, STRUCT_STATFS, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {139, "sysfs", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {140, "getpriority", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {141, "setpriority", {INT, INT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {142, "sched_setparam",
        {INT, STRUCT_SCHED_PARAM, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {143, "sched_getparam",
        {INT, STRUCT_SCHED_PARAM, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {144, "sched_setscheduler",
        {INT, INT, STRUCT_SCHED_PARAM, NO_ARG, NO_ARG, NO_ARG}},
    {145, "sched_getscheduler", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {146, "sched_get_priority_max",
        {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {147, "sched_get_priority_min",
        {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {148, "sched_rr_get_interval",
        {INT, STRUCT_TIMESPEC, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {149, "mlock", {PTR, ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {150, "munlock", {PTR, ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {151, "mlockall", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {152, "munlockall", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {153, "vhangup", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {154, "modify_ldt", {INT, PTR, ULONG, NO_ARG, NO_ARG, NO_ARG}},
    {155, "pivot_root", {STRING, STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {156, "_sysctl",
        {STRUCT___SYSCTL_ARGS, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {157, "prctl", {INT, ULONG, ULONG, ULONG, ULONG, NO_ARG}},
    {158, "arch_prctl", {INT, PTR, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {159, "adjtimex", {STRUCT_TIMEX, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {160, "setrlimit", {INT, STRUCT_RLIMIT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {161, "chroot", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {162, "sync", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {163, "acct", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {164, "settimeofday",
        {STRUCT_TIMEVAL, STRUCT_TIMEZONE, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {165, "mount", {STRING, STRING, STRING, ULONG, PTR, NO_ARG}},
    {166, "umount2", {STRING, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {167, "swapon", {STRING, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {168, "swapoff", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {169, "reboot", {INT, INT, INT, PTR, NO_ARG, NO_ARG}},
    {170, "sethostname", {STRING, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {171, "setdomainname", {STRING, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {172, "iopl", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {173, "ioperm", {ULONG, ULONG, INT, NO_ARG, NO_ARG, NO_ARG}},
    {174, "create_module", {STRING, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {175, "init_module", {ULONG, ULONG, STRING, NO_ARG, NO_ARG, NO_ARG}},
    {176, "delete_module", {STRING, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {177, "get_kernel_syms",
        {STRUCT_KERNEL_SYM, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {178, "query_module", {STRING, INT, PTR, UINT, PTR, NO_ARG}},
    {179, "quotactl", {INT, STRING, INT, ULONG, NO_ARG, NO_ARG}},
    {180, "nfsservctl", {INT, LONG, LONG, NO_ARG, NO_ARG, NO_ARG}},
    {180, "getpmsg", {INT, STRUCT_STRBUF, STRUCT_STRBUF, INT, NO_ARG, NO_ARG}},
    {182, "putpmsg", {INT, STRUCT_STRBUF, STRUCT_STRBUF, INT, NO_ARG, NO_ARG}},
    {183, "afs_syscall", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {184, "tuxcall", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {185, "security", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {186, "gettid", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {187, "readahead", {INT, ULONG, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {188, "setxattr", {STRING, STRING, PTR, UINT, INT, NO_ARG}},
    {189, "lsetxattr", {STRING, STRING, PTR, UINT, INT, NO_ARG}},
    {190, "fsetxattr", {INT, STRING, PTR, UINT, INT, NO_ARG}},
    {191, "getxattr", {STRING, STRING, PTR, UINT, NO_ARG, NO_ARG}},
    {192, "lgetxattr", {STRING, STRING, PTR, UINT, NO_ARG, NO_ARG}},
    {193, "fgetxattr", {INT, STRING, PTR, UINT, NO_ARG, NO_ARG}},
    {194, "listxattr", {STRING, STRING, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {195, "llistxattr", {STRING, STRING, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {196, "flistxattr", {INT, STRING, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {197, "removexattr", {STRING, STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {198, "lremovexattr", {STRING, STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {199, "fremovexattr", {INT, STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {200, "tkill", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {201, "time", {LONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {202, "futex", {PTR, INT, INT, STRUCT_TIMESPEC, PTR, INT}},
    {203, "sched_setaffinity",
        {INT, UINT, STRUCT_CPU_SET, NO_ARG, NO_ARG, NO_ARG}},
    {204, "sched_getaffinity",
        {INT, UINT, STRUCT_CPU_SET, NO_ARG, NO_ARG, NO_ARG}},
    {205, "set_thread_area",
        {STRUCT_USER_DESC, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {206, "io_setup", {UINT, PTR, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {207, "io_destroy", {ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {208, "io_getevents",
        {ULONG, LONG, LONG, STRUCT_IO_EVENT, STRUCT_TIMESPEC, NO_ARG}},
    {209, "io_submit", {ULONG, LONG, STRUCT_IOCB, NO_ARG, NO_ARG, NO_ARG}},
    {210, "io_cancel",
        {ULONG, STRUCT_IOCB, STRUCT_IO_EVENT, NO_ARG, NO_ARG, NO_ARG}},
    {211, "get_thread_area",
        {STRUCT_USER_DESC, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {212, "lookup_dcookie", {ULONG, STRING, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {213, "epoll_create", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {214, "epoll_ctl_old", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {215, "epoll_wait_old", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {216, "remap_file_pages", {PTR, UINT, INT, UINT, INT, NO_ARG}},
    {217, "getdents64",
        {UINT, STRUCT_LINUX_DIRENT64, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {218, "set_tid_address", {PTR, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {219, "restart_syscall", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {220, "semtimedop",
        {INT, STRUCT_SEMBUF, UINT, STRUCT_TIMESPEC, NO_ARG, NO_ARG}},
    {221, "fadvise64", {INT, ULONG, ULONG, INT, NO_ARG, NO_ARG}},
    {222, "timer_create", {INT, STRUCT_SIGEVENT, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {223, "timer_settime",
        {INT, INT, STRUCT_ITIMERSPEC, STRUCT_ITIMERSPEC, NO_ARG, NO_ARG}},
    {224, "timer_gettime",
        {INT, STRUCT_ITIMERSPEC, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {225, "timer_getoverrun", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {226, "timer_delete",
        {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {227, "clock_settime",
        {INT, STRUCT_TIMESPEC, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {228, "clock_gettime",
        {INT, STRUCT_TIMESPEC, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {229, "clock_getres",
        {INT, STRUCT_TIMESPEC, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {230, "clock_nanosleep",
        {INT, INT, STRUCT_TIMESPEC, STRUCT_TIMESPEC, NO_ARG, NO_ARG}},
    {231, "exit_group", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {232, "epoll_wait", {INT, STRUCT_EPOLL_EVENT, INT, INT, NO_ARG, NO_ARG}},
    {233, "epoll_ctl", {INT, INT, INT, STRUCT_EPOLL_EVENT, NO_ARG, NO_ARG}},
    {234, "tgkill", {INT, INT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {235, "utimes", {STRING, STRUCT_TIMEVAL, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {236, "vserver", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {237, "mbind", {PTR, ULONG, INT, PTR, ULONG, UINT}},
    {238, "set_mempolicy", {INT, PTR, ULONG, NO_ARG, NO_ARG, NO_ARG}},
    {239, "get_mempolicy", {PTR, PTR, ULONG, PTR, ULONG, NO_ARG}},
    {240, "mq_open", {STRING, INT, INT, STRUCT_MQ_ATTR, NO_ARG, NO_ARG}},
    {241, "mq_unlink", {STRING, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {242, "mq_timedsend", {INT, STRING, UINT, UINT, STRUCT_TIMESPEC, NO_ARG}},
    {243, "mq_timedreceive", {INT, STRING, UINT, PTR, STRUCT_TIMESPEC, NO_ARG}},
    {244, "mq_notify", {INT, STRUCT_SIGEVENT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {245, "mq_getsetattr",
        {INT, STRUCT_MQ_ATTR, STRUCT_MQ_ATTR, NO_ARG, NO_ARG, NO_ARG}},
    {246, "kexec_load",
        {ULONG, ULONG, STRUCT_KEXEC_SEGMENT, ULONG, NO_ARG, NO_ARG}},
    {247, "waitid", {INT, INT, STRUCT_SIGINFO, INT, NO_ARG, NO_ARG}},
    {248, "add_key", {STRING, STRING, PTR, UINT, INT, NO_ARG}},
    {249, "request_key", {STRING, STRING, STRING, INT, NO_ARG, NO_ARG}},
    {250, "keyctl", {INT, INT, INT, INT, INT, NO_ARG}},
    {251, "ioprio_set", {INT, INT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {252, "ioprio_get", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {253, "inotify_init", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {254, "inotify_add_watch", {INT, STRING, INT, NO_ARG, NO_ARG, NO_ARG}},
    {255, "inotify_rm_watch", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {256, "migrate_pages", {INT, ULONG, PTR, PTR, NO_ARG, NO_ARG}},
    {257, "openat", {INT, STRING, INT, INT, NO_ARG, NO_ARG}},
    {258, "mkdirat", {INT, STRING, INT, NO_ARG, NO_ARG, NO_ARG}},
    {259, "mknodat", {INT, STRING, INT, INT, NO_ARG, NO_ARG}},
    {260, "fchownat", {INT, STRING, INT, INT, INT, NO_ARG}},
    {261, "futimesat", {INT, STRING, STRUCT_TIMEVAL, NO_ARG, NO_ARG, NO_ARG}},
    {262, "newfstatat", {INT, STRING, STRUCT_STAT, INT, NO_ARG, NO_ARG}},
    {263, "unlinkat", {INT, STRING, INT, NO_ARG, NO_ARG, NO_ARG}},
    {264, "renameat", {INT, STRING, INT, STRING, NO_ARG, NO_ARG}},
    {265, "linkat", {INT, STRING, INT, STRING, INT, NO_ARG}},
    {266, "symlinkat", {STRING, INT, STRING, NO_ARG, NO_ARG, NO_ARG}},
    {267, "readlinkat", {INT, STRING, STRING, UINT, NO_ARG, NO_ARG}},
    {268, "fchmodat", {INT, STRING, INT, INT, NO_ARG, NO_ARG}},
    {269, "faccessat", {INT, STRING, INT, INT, NO_ARG, NO_ARG}},
    {270, "pselect6",
        {INT, FDSET, FDSET, FDSET, STRUCT_TIMESPEC, STRUCT_SIGSET}},
    {271, "ppoll",
        {STRUCT_POLLFD, INT, STRUCT_TIMESPEC, STRUCT_SIGSET, NO_ARG, NO_ARG}},
    {272, "unshare", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {273, "set_robust_list",
        {STRUCT_ROBUST_LIST_HEAD, UINT, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {274, "get_robust_list",
        {INT, STRUCT_ROBUST_LIST_HEAD, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {275, "splice", {INT, PTR, INT, PTR, UINT, UINT}},
    {276, "tee", {INT, INT, UINT, UINT, NO_ARG, NO_ARG}},
    {277, "sync_file_range", {INT, LONG, LONG, UINT, NO_ARG, NO_ARG}},
    {278, "vmsplice", {INT, STRUCT_IOVEC, ULONG, UINT, NO_ARG, NO_ARG}},
    {279, "move_pages", {INT, ULONG, PTR, PTR, PTR, INT}},
    {280, "utimensat", {INT, STRING, STRUCT_TIMESPEC, INT, NO_ARG, NO_ARG}},
    {281, "epoll_pwait",
        {INT, STRUCT_EPOLL_EVENT, INT, INT, STRUCT_SIGSET, NO_ARG}},
    {282, "signalfd", {INT, STRUCT_SIGSET, INT, NO_ARG, NO_ARG, NO_ARG}},
    {283, "timerfd_create", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {284, "eventfd", {UINT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {285, "fallocate", {INT, INT, INT, INT, NO_ARG, NO_ARG}},
    {286, "timerfd_settime",
        {INT, INT, STRUCT_ITIMERSPEC, STRUCT_ITIMERSPEC, NO_ARG, NO_ARG}},
    {287, "timerfd_gettime",
        {INT, STRUCT_ITIMERSPEC, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {288, "accept4", {INT, STRUCT_SOCKADDR, UINT, INT, NO_ARG, NO_ARG}},
    {289, "signalfd4", {INT, STRUCT_SIGSET, INT, UINT, NO_ARG, NO_ARG}},
    {290, "eventfd2", {UINT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {291, "epoll_create1", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {292, "dup3", {INT, INT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {293, "pipe2", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {294, "inotify_init1", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {295, "preadv", {INT, STRUCT_IOVEC, INT, INT, NO_ARG, NO_ARG}},
    {296, "pwritev", {INT, STRUCT_IOVEC, INT, INT, NO_ARG, NO_ARG}},
    {297, "rt_tgsigqueueinfo", {INT, INT, INT, STRUCT_SIGINFO, NO_ARG, NO_ARG}},
    {298, "perf_event_open",
        {STRUCT_PERF_EVENT_ATTR, INT, INT, INT, ULONG, NO_ARG}},
    {299, "recvmmsg", {INT, STRUCT_MSGHDR, UINT, INT, STRUCT_TIMESPEC, NO_ARG}},
    {300, "fanotify_init", {UINT, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {301, "fanotify_mark", {INT, UINT, ULONG, INT, STRING, NO_ARG}},
    {302, "prlimit64",
        {INT, INT, STRUCT_RLIMIT64, STRUCT_RLIMIT64, NO_ARG, NO_ARG}},
    {303, "name_to_handle_at",
        {INT, STRING, STRUCT_FILE_HANDLE, PTR, INT, NO_ARG}},
    {304, "open_by_handle_at",
        {INT, STRING, STRUCT_FILE_HANDLE, INT, NO_ARG, NO_ARG}},
    {305, "clock_adjtime", {INT, STRUCT_TIMEX, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {306, "syncfs", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {307, "sendmmsg", {INT, STRUCT_MMSGHDR, UINT, INT, NO_ARG, NO_ARG}},
    {308, "setns", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {309, "getcpu", {PTR, PTR, STRUCT_GETCPU_CACHE, NO_ARG, NO_ARG, NO_ARG}},
    {310, "process_vm_readv",
        {INT, STRUCT_IOVEC, ULONG, STRUCT_IOVEC, ULONG, ULONG}},
    {311, "process_vm_writev",
        {INT, STRUCT_IOVEC, ULONG, STRUCT_IOVEC, ULONG, ULONG}},
    {312, "kcmp", {INT, INT, INT, ULONG, ULONG, NO_ARG}},
    {313, "finit_module", {INT, STRING, INT, NO_ARG, NO_ARG, NO_ARG}},
    {314, "sched_setattr",
        {INT, STRUCT_SCHED_ATTR, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {315, "sched_getattr",
        {INT, STRUCT_SCHED_ATTR, UINT, UINT, NO_ARG, NO_ARG}},
    {316, "renameat2", {INT, STRING, INT, STRING, UINT, NO_ARG}},
    {317, "seccomp", {UINT, UINT, PTR, NO_ARG, NO_ARG, NO_ARG}},
    {318, "getrandom", {PTR, UINT, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {319, "memfd_create", {STRING, UINT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {320, "kexec_file_load", {INT, INT, ULONG, STRING, ULONG, NO_ARG}},
    {321, "bpf", {INT, PTR, UINT, NO_ARG, NO_ARG, NO_ARG}},
    {322, "stub_execveat", {INT, STRING, STRING, STRING, INT, NO_ARG}},
    {323, "userfaultfd", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {324, "membarrier", {INT, INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {325, "mlock2", {PTR, UINT, INT, NO_ARG, NO_ARG, NO_ARG}},
    {326, "copy_file_range", {INT, PTR, INT, PTR, UINT, UINT}},
    {327, "preadv2", {INT, STRUCT_IOVEC, INT, INT, INT, NO_ARG}},
    {328, "pwritev2", {INT, STRUCT_IOVEC, INT, INT, INT, NO_ARG}},
    {329, "pkey_mprotect", {PTR, UINT, INT, INT, NO_ARG, NO_ARG}},
    {330, "pkey_alloc", {ULONG, ULONG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {331, "pkey_free", {INT, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {332, "statx", {INT, STRING, INT, UINT, STRUCT_STATX, NO_ARG}},
    {333, "io_pgetevents", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {334, "rseq", {NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG, NO_ARG}},
    {335, "pkey_mprotect", {PTR, UINT, INT, INT, NO_ARG, NO_ARG}},
};
